Lesson 4 - Algorithms
beglov/go-core-lessons pull request #4
Opened 2020-10-27 13:35 UTC by beglov

2020-10-27 14:19 UTC, beglov commented
Ни массив документов, ни индекс, я специально не сортировал, т.к. на мой взгляд при такой реализации сортировка не требуется.

2020-10-29 14:40 UTC, DmitriyVTitov requested changes
В PR какой-то мусор, какие-то правки во второй урок.
Это проверять невозможно. PR должен весь быть зелёный.

2020-10-29 14:40 UTC, DmitriyVTitov commented on lesson-2/cmd/engine/main.go
>  }
уже не первый раз такое вижу. весьма бессмысленная функция.

2020-10-29 14:40 UTC, DmitriyVTitov commented on lesson-2/cmd/engine/main.go
> +			id = id + 1
как мне разбираться в этих правках, что это вообще за PR с файлами из второго урока?

2020-10-29 14:57 UTC, beglov commented on lesson-2/cmd/engine/main.go
>  }
Да, пожалуй функция бессмысленная. Она делалась в демонстрационных целях в рамках урока по интерфейсам.

2020-10-29 14:59 UTC, DmitriyVTitov commented on lesson-2/cmd/engine/main.go
>  }
ну так добавьте туда, например,  сканирование по массиву ссылок.
будет какой-никакой но смысл, какая-то дополнительная, привнесённая логика.

2020-10-29 15:06 UTC, beglov commented
Я не стал создавать отдельную папку для этого урока, т.к. мы фактически продолжаем работу начатую на предыдущих занятиях(возможно стоило переименовать её из lesson-2 в скажем websearch). В этом PR только изменения относящиеся непосредственно к уроку по алгоритмам. Я думал что так будет наоборот удобнее проверять, но ок, если нужно что бы все было зеленое, то будет зеленое...

2020-10-29 15:13 UTC, DmitriyVTitov commented
> Я не стал создавать отдельную папку для этого урока, т.к. мы фактически продолжаем работу начатую на предыдущих занятиях(возможно стоило переименовать её из lesson-2 в скажем websearch). В этом PR только изменения относящиеся непосредственно к уроку по алгоритмам. Я думал что так будет наоборот удобнее проверять, но ок, если нужно что бы все было зеленое, то будет зеленое...

нужно зелёное, так понятнее, и все лишние файлы при копировании тоже удалите, пожалуйста

2020-10-30 07:35 UTC, beglov commented
Сделал в отдельной папке для 4 урока.

2020-11-01 12:00 UTC, DmitriyVTitov requested changes
Ваш индекс получился одноразовым. Нужно разделить конструктор и метод по обработке документов.
Ну и другие замечания посмотрите.

2020-11-01 12:00 UTC, DmitriyVTitov commented on lesson-4/cmd/engine/main.go
> +}
функция ищет и что? печатает на экран?
а как это протестировать?
гораздо лучше, если бы функция возвращала результат, а печатать его или ещё что решал бы вызывающий код

2020-11-01 12:00 UTC, DmitriyVTitov commented on lesson-4/cmd/engine/main.go
> +			fmt.Printf("%s - %s\n", data[v].URL, data[v].Title)
нежелательный побочный эффект

2020-11-01 12:00 UTC, DmitriyVTitov commented on lesson-4/cmd/engine/main.go
> +func binary(data []spider.Document, item int) int {
название неудачное. если это поиск, то и называться функция должна соответствующе.

2020-11-01 12:00 UTC, DmitriyVTitov commented on lesson-4/pkg/index/index.go
> +func New(documents []spider.Document) *Service {
конструктор должен создавать и инициализировать объект по минимуму.
обработка данных - не задача конструктора.

2020-11-01 12:00 UTC, DmitriyVTitov commented on lesson-4/pkg/index/index.go
> +func New(documents []spider.Document) *Service {
вот захотел я добавить документы и что мне делать? снова конструктор вызывать? так это ещё один индекс, не правильно как-то.

2020-11-05 20:03 UTC, DmitriyVTitov approved these changes
Принято!

2020-11-05 20:03 UTC, DmitriyVTitov commented on lesson-4/pkg/index/index.go
> +		}
ещё бы надо уникальность проверять

2020-11-06 09:46 UTC, merged