Lesson 6 - IO
beglov/go-core-lessons pull request #6
Opened 2020-11-12 20:34 UTC by beglov

2020-11-15 01:43 UTC, DmitriyVTitov requested changes
Если в функции может возникнуть ошибка, то функция должна её вернуть. Почти всегда это так.
Обрабатывать ошибки должен вызывающий код.

2020-11-15 01:43 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +	go gs.scan()
OK

2020-11-15 01:43 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +	}
в таких случаях функции следует вернуть ошибку, а вызывающий код уже решит: напечатать её или что-то ещё

2020-11-15 01:43 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +	}
и что? никто этих надписей не читает.

2020-11-15 01:43 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +}
опять функция работает с диском, но ошибку не возвращает

2020-11-15 01:43 UTC, DmitriyVTitov commented
Проанализируйте ещё раз все свои функции и поправьте работу с ошибками.

2020-11-19 05:58 UTC, DmitriyVTitov requested changes
Замечания не исправлены. Ошибки всё так же игнорируются.
Не принимаю.

2020-11-19 05:58 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +		}
не удалось и что? и продолжаем как будто удалось?
именно к этому и была претензия в прошлой рецензии.
я не буду подсказывать, но это поведение должно быть очевидно изменено.

2020-11-19 08:55 UTC, beglov commented on lesson-6/cmd/search/main.go
> +		}
Не очень понимаю что здесь нужно изменить. Мы пытаемся восстановить предыдущие результаты и в случае невозможности это сделать, сообщаем об этом пользователю и ждем пока пройдет новое сканирование. Не завершать же работу программы из за этого.

2020-11-19 10:32 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +		}
> Мы пытаемся восстановить предыдущие результаты и в случае невозможности это сделать, сообщаем об этом пользователю и ждем пока пройдет новое сканирование.

В том-то и дело, что не ждём. У вас запускается функция сканирования в отдельном потоке и программа сразу продолжает работу, хотя сканирование ещё не завершилось.
Конечно, конкурентное программирование мы начнём изучать только сегодня, но уже здесь можно сделать как: если ошибка, то запустить сканирование синхронно (без `go ...`), а если ошибки нет и всё загрузилось - то асинхронно (с `go ...`).
Если я правильно понял логику работы, конечно.

2020-11-19 11:41 UTC, beglov commented on lesson-6/cmd/search/main.go
> +		}
Да, действительно. Поправил это дело.

2020-11-20 03:30 UTC, DmitriyVTitov approved these changes
OK, но пара замечаний таки есть.

2020-11-20 03:30 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +}
в этих `else` чёрт ногу сломит.
старайтесь вообще не использовать `else`

```
if X ...
if !X ...
```

2020-11-20 03:30 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +			log.Println("не удалось восстановить результаты предыдущего сканирования", err)
эти сообщения на сервере никто не читает

2020-11-20 03:30 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +	log.Println("Восстановление результатов предыдущего сканирования...")
и это никто не прочитает

2020-11-20 03:30 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +	return nil
заменить на `return err`

2020-11-20 03:30 UTC, DmitriyVTitov commented on lesson-6/pkg/engine/engine.go
> +}
прочитайте комментарий в начале файла. там есть что-то про добавление документов? нет :)

2020-11-20 03:30 UTC, DmitriyVTitov commented on lesson-6/pkg/engine/engine.go
> +	return nil
`return err`
возьмите на вооружение

2020-11-23 18:28 UTC, beglov commented on lesson-6/cmd/search/main.go
> +	return nil
Не понял зачем заменять на `return err`, кажется в лекциях наоборот говорилось что при отсутствии ошибки лучше явно вернуть `nil`

2020-11-23 18:30 UTC, DmitriyVTitov commented on lesson-6/cmd/search/main.go
> +	return nil
да, верно, но тут экономятся несколько строчек. так что есть плюсы.
и к тому же это избавит вас от бессмысленной log.Println().
на сервере никто этих надписей не увидит.

2020-11-23 18:36 UTC, beglov commented on lesson-6/cmd/search/main.go
> +	return nil
А, все понял, можно избавиться от проверки на `nil` и просто делать `return err`

2020-11-23 19:08 UTC, merged