Lesson 9 - Benchmark
beglov/go-core-lessons pull request #9
Opened 2021-01-15 13:51 UTC by beglov

```
beglov@laptop:~/projects/go-core-lessons/lesson-9/pkg/storage$ go test -bench . -benchmem ./...
?       go-core-lessons/lesson-9/pkg/storage    [no test files]
goos: linux
goarch: amd64
pkg: go-core-lessons/lesson-9/pkg/storage/btree
BenchmarkTree_InsertSearch-12              19564            118607 ns/op              80 B/op          1 allocs/op
PASS
ok      go-core-lessons/lesson-9/pkg/storage/btree      2.937s
goos: linux
goarch: amd64
pkg: go-core-lessons/lesson-9/pkg/storage/slice
BenchmarkSlice_InsertSearch-12             92662            124701 ns/op             286 B/op          0 allocs/op
PASS
ok      go-core-lessons/lesson-9/pkg/storage/slice      11.689s
```

2021-01-15 16:22 UTC, DmitriyVTitov requested changes
Пожалуй не приму.

2021-01-15 16:22 UTC, DmitriyVTitov commented on lesson-9/pkg/storage/btree/btree_test.go
> +}
не! тут как в модульных тестах: одна функция - один замер. (от этого можно отойти, но тут причины нет).
т.е. надо разделять операции. тем более, что операции вставки (записи) и поиска (чтения) имеют принципиально разный профиль работы с хранилищем.
иногда под них делают разные БД (см. CQRS)

2021-01-15 16:22 UTC, DmitriyVTitov commented on lesson-9/pkg/storage/slice/slice_test.go
> +}
ну и тут тоже

2021-01-18 10:07 UTC, beglov commented
Сделал отдельные замеры для операций добавления документов и поиска. Также переделал в табличный вид для разного размера хранилища.
```
beglov@laptop:~/projects/go-core-lessons/lesson-9/pkg/storage$ go test -bench . -benchmem ./...
?       go-core-lessons/lesson-9/pkg/storage    [no test files]
goos: linux
goarch: amd64
pkg: go-core-lessons/lesson-9/pkg/storage/btree
BenchmarkTree_StoreDocs/Тест_№1-12                         19670            246340 ns/op             160 B/op          2 allocs/op
BenchmarkTree_StoreDocs/Тест_№2-12                         10000            571651 ns/op             880 B/op         11 allocs/op
BenchmarkTree_StoreDocs/Тест_№3-12                         10000          10315792 ns/op            8080 B/op        101 allocs/op
BenchmarkTree_Search/Тест_№1-12                         133400889                8.87 ns/op            0 B/op          0 allocs/op
BenchmarkTree_Search/Тест_№2-12                         29169434                38.6 ns/op             0 B/op          0 allocs/op
BenchmarkTree_Search/Тест_№3-12                          3059046               389 ns/op               0 B/op          0 allocs/op
PASS
ok      go-core-lessons/lesson-9/pkg/storage/btree      119.205s
goos: linux
goarch: amd64
pkg: go-core-lessons/lesson-9/pkg/storage/slice
BenchmarkSlice_StoreDocs/Тест_№1-12                      3974382               296 ns/op             584 B/op          0 allocs/op
BenchmarkSlice_StoreDocs/Тест_№2-12                       987367              1835 ns/op            4200 B/op          0 allocs/op
BenchmarkSlice_StoreDocs/Тест_№3-12                        84757             12087 ns/op           33265 B/op          0 allocs/op
BenchmarkSlice_Search/Тест_№1-12                        151941362                7.89 ns/op            0 B/op          0 allocs/op
BenchmarkSlice_Search/Тест_№2-12                        44105548                27.4 ns/op             0 B/op          0 allocs/op
BenchmarkSlice_Search/Тест_№3-12                         5216816               224 ns/op               0 B/op          0 allocs/op
PASS
ok      go-core-lessons/lesson-9/pkg/storage/slice      10.122s
```

P.S. Судя по результатам реализация в виде slice эффективней...

2021-01-20 13:16 UTC, DmitriyVTitov commented
> Сделал отдельные замеры для операций добавления документов и поиска. Также переделал в табличный вид для разного размера хранилища.
> 
> ```
> beglov@laptop:~/projects/go-core-lessons/lesson-9/pkg/storage$ go test -bench . -benchmem ./...
> ?       go-core-lessons/lesson-9/pkg/storage    [no test files]
> goos: linux
> goarch: amd64
> pkg: go-core-lessons/lesson-9/pkg/storage/btree
> BenchmarkTree_StoreDocs/Тест_№1-12                         19670            246340 ns/op             160 B/op          2 allocs/op
> BenchmarkTree_StoreDocs/Тест_№2-12                         10000            571651 ns/op             880 B/op         11 allocs/op
> BenchmarkTree_StoreDocs/Тест_№3-12                         10000          10315792 ns/op            8080 B/op        101 allocs/op
> BenchmarkTree_Search/Тест_№1-12                         133400889                8.87 ns/op            0 B/op          0 allocs/op
> BenchmarkTree_Search/Тест_№2-12                         29169434                38.6 ns/op             0 B/op          0 allocs/op
> BenchmarkTree_Search/Тест_№3-12                          3059046               389 ns/op               0 B/op          0 allocs/op
> PASS
> ok      go-core-lessons/lesson-9/pkg/storage/btree      119.205s
> goos: linux
> goarch: amd64
> pkg: go-core-lessons/lesson-9/pkg/storage/slice
> BenchmarkSlice_StoreDocs/Тест_№1-12                      3974382               296 ns/op             584 B/op          0 allocs/op
> BenchmarkSlice_StoreDocs/Тест_№2-12                       987367              1835 ns/op            4200 B/op          0 allocs/op
> BenchmarkSlice_StoreDocs/Тест_№3-12                        84757             12087 ns/op           33265 B/op          0 allocs/op
> BenchmarkSlice_Search/Тест_№1-12                        151941362                7.89 ns/op            0 B/op          0 allocs/op
> BenchmarkSlice_Search/Тест_№2-12                        44105548                27.4 ns/op             0 B/op          0 allocs/op
> BenchmarkSlice_Search/Тест_№3-12                         5216816               224 ns/op               0 B/op          0 allocs/op
> PASS
> ok      go-core-lessons/lesson-9/pkg/storage/slice      10.122s
> ```
> 
> P.S. Судя по результатам реализация в виде slice эффективней...

Да, хотя дерево должно быть быстрее в смысле хранения данных. Но тут много нюансов, поэтому я и говорил многократно, что не стоит рассчитывать на особенности внутренней реализации языка.
У меня и многих других студентов дерево получилось в 10 раз быстрее на вставку.

2021-01-20 13:18 UTC, DmitriyVTitov approved these changes
OK

2021-01-21 12:07 UTC, merged